### PR TITLE
Upgrade to aws sdk v2 and fix issue #7

### PR DESCRIPTION
**Pull request by aymanbagabas**

### CODE REVIEW

**Comment by PhoenixPeca** [comment]
Hi @aymanbagabas , please help to resolve the merge conflicts.
Thank you so much!

**Comment by aymanbagabas** [comment]
@PhoenixPeca conflicts resolved!

**Comment by PhoenixPeca** [comment]
Thank you so much @aymanbagabas ! I will check to make a release soon!

**Comment by aymanbagabas** [comment]
@PhoenixPeca do you need anything else from my end?

**Comment by kwypchlo** [comment]
@PhoenixPeca do you think you could take another look at this pull request? I'm having issues with route53 and with a bit of luck an update like this might actually fix #11

**Comment by aymanbagabas** [comment]
> If maintainer is inactive, would anyone here like to take up a maintainership role for this repo?

@mholt I wouldn't mind taking that role.

**Comment by mholt** [comment]
@aymanbagabas Sounds good, invite on its way in a moment. I like @charmbracelet btw!

**Comment by aymanbagabas** [comment]
> @aymanbagabas Sounds good, invite on its way in a moment. I like @charmbracelet btw!

Thank you! Merging this one...

**Pull request merged**
