### PR TITLE
Fix static creds init & support skipping waiting for record propagation

### PR DESCRIPTION
**Pull request by aymanbagabas**
Fixes: https://github.com/libdns/route53/issues/14
Fixes: https://github.com/libdns/route53/issues/13

### CODE REVIEW

**Comment by aymanbagabas** [comment]
@mr-karan if you have the time, could you try this [patch](https://github.com/libdns/route53/pull/15.patch)?

**Comment by mholt** [comment]
(Thanks for maintaining this!)

I think generally it is best practice to not implement your own waiting for propagation. (But I'm not familiar with Route53, maybe that's needed?)

In any case, if this is used in conjunction with CertMagic/Caddy for the DNS challenge, it has its own Wait() facility that handles it for you: https://pkg.go.dev/github.com/caddyserver/certmagic#DNS01Solver.Wait

Just FYI.

**Comment by aymanbagabas** [comment]
@mholt good point, in that case, we don't really need to implement our own waiting for propagation. However, it can be helpful if this is used with something other than CertMagic/Caddy. I'll make this disabled by default.

**Comment by mr-karan** [comment]
@aymanbagabas Yep it works. Thanks! 

And yeah - disabled by default should cover the general usecase.

**Pull request merged**
