### PR TITLE
Fix TXT records

### PR DESCRIPTION
**Pull request by aymanbagabas**
This is basically a hack since route53 doesn't really support multiple TXT records.

TODO:
- [x] Delete TXT records
- [x] Set multiple TXT records

Fix: Unquote TXT records
Fix: Unquote/Quote SPF records
Fix: Correct returned records name

TXT records Catch:
* record TTL will be set to the last TXT record TTL
* TXT records will always be upserted i.e. it won't fail if TXT record already exists

Fixes: https://github.com/libdns/route53/issues/17
Fixes: https://github.com/libdns/route53/issues/16

### CODE REVIEW

**Review by mholt — COMMENTED** [review]
Thanks for fixing this!

I don't use Route53 so I'm trusting you've tested that it works :smile: If so, LGTM!

**Review by tuckstarrydell — APPROVED** [review]
fix

**Comment by blarghmatey** [comment]
Is there any ETA on when this might get merged? This seems like it would resolve an existing bug in https://github.com/caddy-dns/route53 as well if it can get merged and incorporated into a new release of that project.

**Comment by aymanbagabas** [comment]
A very hacky approach, but needed. Merging this...

**Pull request merged**
